language: android
jdk: oraclejdk8
android:
    licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+' 
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - add-on
    - extra
before_cache:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
